add l_2
OrlovSA/-JavaScript_Basics pull request #2
Opened 2021-03-25 10:43 UTC by OrlovSA

2021-03-25 14:43 UTC, Om1X requested changes

2021-03-25 14:43 UTC, Om1X commented on Lesson2/script_js_2.js
> +        }
зачем?

2021-03-25 14:43 UTC, Om1X commented on Lesson2/script_js_2.js
> +}
не верно, т.к. функция возвращает undefined, а должна возвращать результат

2021-03-25 14:43 UTC, Om1X commented on Lesson2/script_js_2.js
> +        case "division": return mathOperationDivision(a, b);
аналогично, получим undefined

2021-03-26 03:44 UTC, OrlovSA commented on Lesson2/script_js_2.js
> +        }
точно, поспешил

2021-03-30 10:59 UTC, merged